name: moneymaxxing
description: "A personal finance management app designed to make savings addictive."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  idb_shim: ^2.3.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.0
  fl_chart: ^0.64.0 
  flutter_gemini: ^3.0.0 
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true